manipulator:
  kinematics_solver: ur_kinematics/UR5KinematicsPlugin
    #trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
    #kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver_search_resolution: 0.005
  #solve_type: Distance
  #kinematics_solver_timeout: 0.05
  #kinematics_solver_attempts: 20
